# Introducción a Pandas

![Introducción](https://drive.google.com/uc?id=1rOYbONOI2d7LJ0i6btU_tNksgPu_04Qj)

El primer paso es importar pandas. Para ello haremos uso de la sintaxis en python:
<br/>
<br/>
import pandas as pd
<br/>
<br/>
Usaremos el alias "pd" para evitar escribir pandas a cada rato

In [ ]:
import pandas as pd

La introducción la realizaremos con el siguiente dataset, el cual es un excel:
<br/>
<br/>
https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv

Podemos descargar manualmente el dataset para su posterior lectura:

In [ ]:
#Descarga del dataset
!wget https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv

--2024-07-09 14:46:30--  https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 18276 (18K) [text/plain]
Saving to: ‘Auto.csv’

Auto.csv            100%[===================>]  17.85K  --.-KB/s    in 0s

2024-07-09 14:46:30 (81.5 MB/s) - ‘Auto.csv’ saved [18276/18276]

In [ ]:
#Comprobamos que efectivamente se ha descargado el dataset. Deberíamos ver un archivo llamado Auto.csv
%ls -l

total 24
-rw-r--r-- 1 root root 18276 Jul  9 14:46 Auto.csv
drwxr-xr-x 1 root root  4096 Jul  3 13:21 sample_data/

In [ ]:
#Lectura del dataset
file_name = "Auto.csv"

#El método "read_csv" nos permite leer un excel
dataset = pd.read_csv(file_name)

O también podemos hacer que pandas descargue el dataset por nosotros:

In [ ]:
#Descarga y lectura del dataset
url = "https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv"

#El método "read_csv" nos permite leer un excel
dataset = pd.read_csv(url)

Por defecto al leer un excel con "read_csv", éste se almacena en un DataFrame perteneciente a pandas

In [ ]:
print(type(dataset))

<class 'pandas.core.frame.DataFrame'>

Para saber las columnas que contiene nuestro DataFrame haremos uso del atributo "columns":

In [ ]:
print(dataset.columns)

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'year', 'origin', 'name'],
      dtype='object')

Para saber el tipo de dato de nuestras columnas hacemos uso de la propiedad "dtypes":

In [ ]:
#Visualizamos el tipo de dato de las columnas
print(dataset.dtypes)

mpg             float64
cylinders         int64
displacement    float64
horsepower        int64
weight            int64
acceleration    float64
year              int64
origin            int64
name             object
dtype: object

Las variables puestas al final de una celda del notebook serán imprimidas automáticamente:

In [ ]:
#Operaciones aleatorias
variable_1 = 5 + 8

variable_2 = 10 + 7

variable_1, variable_2

(13, 17)

Hagamos lo mismo con nuestro DataFrame:

In [ ]:
dataset

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
387,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
388,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
389,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
390,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
391,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

Si quisieramos ver sólo las primeras filas del dataset usaremos el método "head":

In [ ]:
#Por defecto el método "head" mostrará las primeras 5 filas
dataset.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [ ]:
#Especificando la cantidad de filas a visualizar
number_of_rows = 10

dataset.head(number_of_rows)

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
5,15.0,8,429.0,198,4341,10.0,70,1,ford galaxie 500
6,14.0,8,454.0,220,4354,9.0,70,1,chevrolet impala
7,14.0,8,440.0,215,4312,8.5,70,1,plymouth fury iii
8,14.0,8,455.0,225,4425,10.0,70,1,pontiac catalina
9,15.0,8,390.0,190,3850,8.5,70,1,amc ambassador dpl

Si quisieramos ver sólo las últimas filas del dataset usaremos el método "tail":

In [ ]:
#Por defecto el método "tail" mostrará las últimas 5 filas
dataset.tail()

      mpg  cylinders  displacement  ...  year  origin             name
387  27.0          4         140.0  ...    82       1  ford mustang gl
388  44.0          4          97.0  ...    82       2        vw pickup
389  32.0          4         135.0  ...    82       1    dodge rampage
390  28.0          4         120.0  ...    82       1      ford ranger
391  31.0          4         119.0  ...    82       1       chevy s-10

[5 rows x 9 columns]

In [ ]:
#Especificando la cantidad de filas a visualizar
number_of_rows = 10

dataset.tail(number_of_rows)

      mpg  cylinders  displacement  ...  year  origin                        name
382  26.0          4         156.0  ...    82       1  chrysler lebaron medallion
383  22.0          6         232.0  ...    82       1              ford granada l
384  32.0          4         144.0  ...    82       3            toyota celica gt
385  36.0          4         135.0  ...    82       1           dodge charger 2.2
386  27.0          4         151.0  ...    82       1            chevrolet camaro
387  27.0          4         140.0  ...    82       1             ford mustang gl
388  44.0          4          97.0  ...    82       2                   vw pickup
389  32.0          4         135.0  ...    82       1               dodge rampage
390  28.0          4         120.0  ...    82       1                 ford ranger
391  31.0          4         119.0  ...    82       1                  chevy s-10

[10 rows x 9 columns]

Para saber la cantidad de filas y columnas de nuestro dataset usaremos el método "shape" que nos devolverá una tupla con el siguiente formato: (cantidad de filas, cantidad de columnas)

In [ ]:
#Deberíamos constatar que el dataset que estamos usando tiene 392 filas y 9 columnas
dataset.shape

(392, 9)

Para observar una columna en particular haremos uso de sus nombres:

In [ ]:
#Observación de una columna usando los corchetes
column_name = "acceleration"

dataset[column_name]

0      12.0
1      11.5
2      11.0
3      12.0
4      10.5
       ...
387    15.6
388    24.6
389    11.6
390    18.6
391    19.4
Name: acceleration, Length: 392, dtype: float64

In [ ]:
#Observación de una columna usando el nombre de la columna como un atributo
dataset.acceleration

0      12.0
1      11.5
2      11.0
3      12.0
4      10.5
       ...
387    15.6
388    24.6
389    11.6
390    18.6
391    19.4
Name: acceleration, Length: 392, dtype: float64

Para observar varias columnas a la vez usaremos doble corchetes:

In [ ]:
dataset[["mpg", "name"]]

      mpg                       name
0    18.0  chevrolet chevelle malibu
1    15.0          buick skylark 320
2    18.0         plymouth satellite
3    16.0              amc rebel sst
4    17.0                ford torino
..    ...                        ...
387  27.0            ford mustang gl
388  44.0                  vw pickup
389  32.0              dodge rampage
390  28.0                ford ranger
391  31.0                 chevy s-10

[392 rows x 2 columns]

Cuando obtenemos columnas de nuestro DataFrame, éstas a su vez son DataFrame. De esta forma podemos aplicar lo que hemos visto sobre las columnas:

In [ ]:
dataset["mpg"].head()

0    18.0
1    15.0
2    18.0
3    16.0
4    17.0
Name: mpg, dtype: float64

In [ ]:
dataset.name.tail()

387    ford mustang gl
388          vw pickup
389      dodge rampage
390        ford ranger
391         chevy s-10
Name: name, dtype: object

In [ ]:
dataset[["mpg", "name"]].head(7)

    mpg                       name
0  18.0  chevrolet chevelle malibu
1  15.0          buick skylark 320
2  18.0         plymouth satellite
3  16.0              amc rebel sst
4  17.0                ford torino
5  15.0           ford galaxie 500
6  14.0           chevrolet impala

También podemos crear nuestro propio DataFrame desde cero:

In [ ]:
columns = ["Carrera", "Facultad"]

data = [ ["Ingeniería Informática", "Ciencias e Ingeniería"],
         ["Antropología", "Ciencias Sociales"],
         ["Contabilidad", "Ciencias Contables"],
         ["Física", "Ciencias e Ingeniería"],
         ["Diseño Gráfico", "Arte y Diseño"],
         ["Física", "Ciencias e Ingeniería"] ]

dataset = pd.DataFrame(data=data, columns=columns)

dataset

                  Carrera               Facultad
0  Ingeniería Informática  Ciencias e Ingeniería
1            Antropología      Ciencias Sociales
2            Contabilidad     Ciencias Contables
3                  Física  Ciencias e Ingeniería
4          Diseño Gráfico          Arte y Diseño
5                  Física  Ciencias e Ingeniería

Para agregar/reemplazar filas a un DataFrame haremos uso de la propiedad "loc":

In [ ]:
#Agregando filas
dataset.loc[2] = ["No definido", "No definido"]

dataset.loc[6] = ["Contabilidad", "Ciencias Contables"]

dataset

                  Carrera               Facultad
0  Ingeniería Informática  Ciencias e Ingeniería
1            Antropología      Ciencias Sociales
2             No definido            No definido
3                  Física  Ciencias e Ingeniería
4          Diseño Gráfico          Arte y Diseño
5                  Física  Ciencias e Ingeniería
6            Contabilidad     Ciencias Contables

In [ ]:
#Reemplazando una fila
dataset.loc[1] = ["Derecho", "Derecho"]

dataset

                  Carrera               Facultad
0  Ingeniería Informática  Ciencias e Ingeniería
1                 Derecho                Derecho
2             No definido            No definido
3                  Física  Ciencias e Ingeniería
4          Diseño Gráfico          Arte y Diseño
5                  Física  Ciencias e Ingeniería
6            Contabilidad     Ciencias Contables

Filtrando mediante valores booleanos

In [ ]:
condition = (dataset["Facultad"] == "Derecho")

condition

0    False
1     True
2    False
3    False
4    False
5    False
6    False
Name: Facultad, dtype: bool

In [ ]:
dataset[condition]

   Carrera Facultad
1  Derecho  Derecho

In [ ]:
condition = (dataset["Carrera"] == "Física") & (dataset["Facultad"] == "Ciencias e Ingeniería")

condition

0    False
1    False
2    False
3     True
4    False
5     True
6    False
dtype: bool

In [ ]:
dataset[condition]

  Carrera               Facultad
3  Física  Ciencias e Ingeniería
5  Física  Ciencias e Ingeniería

Conteo de registros

In [ ]:
dataset.value_counts()

Carrera                 Facultad
Física                  Ciencias e Ingeniería    2
Contabilidad            Ciencias Contables       1
Derecho                 Derecho                  1
Diseño Gráfico          Arte y Diseño            1
Ingeniería Informática  Ciencias e Ingeniería    1
No definido             No definido              1
dtype: int64

In [ ]:
dataset["Carrera"].value_counts()

Física                    2
Ingeniería Informática    1
Derecho                   1
No definido               1
Diseño Gráfico            1
Contabilidad              1
Name: Carrera, dtype: int64

In [ ]:
dataset["Facultad"].value_counts()

Ciencias e Ingeniería    3
Derecho                  1
No definido              1
Arte y Diseño            1
Ciencias Contables       1
Name: Facultad, dtype: int64

In [ ]:
condition = (dataset["Facultad"] == "Ciencias e Ingeniería")

condition.value_counts()

False    4
True     3
Name: Facultad, dtype: int64

In [ ]:
dataset[condition].value_counts()

Carrera                 Facultad
Física                  Ciencias e Ingeniería    2
Ingeniería Informática  Ciencias e Ingeniería    1
dtype: int64

Para agregar columnas a nuestro DataFrame haremos uso de los corchetes:

In [ ]:
data = [1, 2, "3", 4, "5", 6, "7"]

dataset["Nueva Columna"] = data

dataset

                  Carrera               Facultad Nueva Columna
0  Ingeniería Informática  Ciencias e Ingeniería             1
1                 Derecho                Derecho             2
2             No definido            No definido             3
3                  Física  Ciencias e Ingeniería             4
4          Diseño Gráfico          Arte y Diseño             5
5                  Física  Ciencias e Ingeniería             6
6            Contabilidad     Ciencias Contables             7

Dado que la columna tiene un nombre compuesto por espacios, accederemos a ella mediante los corchetes:

In [ ]:
dataset["Nueva Columna"].head(2)

0    1
1    2
Name: Nueva Columna, dtype: object

Para reemplazar los valores de una columna basta acceder a ella y establecer los nuevos valores:

In [ ]:
dataset["Nueva Columna"] = [10, 11, 12, 13, 14, 15, 16]

dataset

                  Carrera               Facultad  Nueva Columna
0  Ingeniería Informática  Ciencias e Ingeniería             10
1                 Derecho                Derecho             11
2             No definido            No definido             12
3                  Física  Ciencias e Ingeniería             13
4          Diseño Gráfico          Arte y Diseño             14
5                  Física  Ciencias e Ingeniería             15
6            Contabilidad     Ciencias Contables             16

Si quisieramos reemplazar un valor en valor en específico, haremos uso de la columna y el índice de la fila:

In [ ]:
#Haciendo uso de la propiedad "at"
row_index = 5

column_name = "Nueva Columna"

dataset.at[row_index, column_name] = 20

dataset

                  Carrera               Facultad  Nueva Columna
0  Ingeniería Informática  Ciencias e Ingeniería             10
1                 Derecho                Derecho             11
2             No definido            No definido             12
3                  Física  Ciencias e Ingeniería             13
4          Diseño Gráfico          Arte y Diseño             14
5                  Física  Ciencias e Ingeniería             20
6            Contabilidad     Ciencias Contables             16

Pandas nos permite manipular fechas mediante el método "Timestamp", que verificará que el dato introducido sea correcto:

In [ ]:
#Creamos una fecha cuyo formato es: año mes día hora minuto segundo
date = "20200229013010"

pd.Timestamp(date)

Timestamp('2020-02-29 01:30:10')

In [ ]:
#Tratamos de crear la fecha 29 de febrero del 2019 la cual es inválida. Deberíamos ver la impresión "could not convert string to Timestamp"
date = "20190229013010"

try:
  pd.Timestamp(date)
except Exception as e:
 print(e)

could not convert string to Timestamp

Reemplazamos el nombre y valores de la columna que creamos con fechas

In [ ]:
#Cambiamos el nombre de la columna
dataset.rename(columns={"Nueva Columna": "Timestamp"}, inplace=True)

dataset

                  Carrera               Facultad  Timestamp
0  Ingeniería Informática  Ciencias e Ingeniería         10
1                 Derecho                Derecho         11
2             No definido            No definido         12
3                  Física  Ciencias e Ingeniería         13
4          Diseño Gráfico          Arte y Diseño         14
5                  Física  Ciencias e Ingeniería         20
6            Contabilidad     Ciencias Contables         16

In [ ]:
#Cambiando los valores de la columna. Si ponemos un sólo valor, éste se repetirá para todas las filas
dataset["Timestamp"] = 20

dataset

                  Carrera               Facultad  Timestamp
0  Ingeniería Informática  Ciencias e Ingeniería         20
1                 Derecho                Derecho         20
2             No definido            No definido         20
3                  Física  Ciencias e Ingeniería         20
4          Diseño Gráfico          Arte y Diseño         20
5                  Física  Ciencias e Ingeniería         20
6            Contabilidad     Ciencias Contables         20

In [ ]:
#Cambiando los valores de la columna usando las fechas
date = "20200101"

dataset["Timestamp"] = pd.Timestamp(date)

dataset

                  Carrera               Facultad  Timestamp
0  Ingeniería Informática  Ciencias e Ingeniería 2020-01-01
1                 Derecho                Derecho 2020-01-01
2             No definido            No definido 2020-01-01
3                  Física  Ciencias e Ingeniería 2020-01-01
4          Diseño Gráfico          Arte y Diseño 2020-01-01
5                  Física  Ciencias e Ingeniería 2020-01-01
6            Contabilidad     Ciencias Contables 2020-01-01

In [ ]:
#Visualizamos el tipo de dato de las columnas
dataset.dtypes

Carrera              object
Facultad             object
Timestamp    datetime64[ns]
dtype: object

En caso ya tengamos las fechas como cadenas de texto, podemos transformar dichas cadenas de texto al tipo de dato fecha:

In [ ]:
#Modificamos las fechas a cadenas de texto
dataset["Timestamp"] = "20200101"

dataset

                  Carrera               Facultad Timestamp
0  Ingeniería Informática  Ciencias e Ingeniería  20200101
1                 Derecho                Derecho  20200101
2             No definido            No definido  20200101
3                  Física  Ciencias e Ingeniería  20200101
4          Diseño Gráfico          Arte y Diseño  20200101
5                  Física  Ciencias e Ingeniería  20200101
6            Contabilidad     Ciencias Contables  20200101

In [ ]:
#Modificamos las cadenas de texto al tipo de dato fecha
#Para ver los formatos disponibles revisar https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior
dataset["Timestamp"] =  pd.to_datetime(dataset["Timestamp"], format="%Y%m%d")

dataset

                  Carrera               Facultad  Timestamp
0  Ingeniería Informática  Ciencias e Ingeniería 2020-01-01
1                 Derecho                Derecho 2020-01-01
2             No definido            No definido 2020-01-01
3                  Física  Ciencias e Ingeniería 2020-01-01
4          Diseño Gráfico          Arte y Diseño 2020-01-01
5                  Física  Ciencias e Ingeniería 2020-01-01
6            Contabilidad     Ciencias Contables 2020-01-01

In [ ]:
#Visualizamos el tipo de dato de las columnas
dataset.dtypes

Carrera      object
Facultad     object
Timestamp    object
dtype: object

Agrupamientos

In [ ]:
dataset.groupby("Carrera").size()

Carrera
Contabilidad              1
Derecho                   1
Diseño Gráfico            1
Física                    2
Ingeniería Informática    1
No definido               1
dtype: int64

In [ ]:
dataset.groupby("Carrera").count()

                        Facultad  Timestamp
Carrera
Contabilidad                   1          1
Derecho                        1          1
Diseño Gráfico                 1          1
Física                         2          2
Ingeniería Informática         1          1
No definido                    1          1

In [ ]:
dataset.groupby("Facultad").size()

Facultad
Arte y Diseño            1
Ciencias Contables       1
Ciencias e Ingeniería    3
Derecho                  1
No definido              1
dtype: int64

In [ ]:
dataset.groupby("Facultad").count()

                       Carrera  Timestamp
Facultad
Arte y Diseño                1          1
Ciencias Contables           1          1
Ciencias e Ingeniería        3          3
Derecho                      1          1
No definido                  1          1

In [ ]:
dataset.groupby("Timestamp").size()

Timestamp
2020-01-01    7
dtype: int64

In [ ]:
dataset.groupby("Timestamp").count()

            Carrera  Facultad
Timestamp
2020-01-01        7         7